[package]
name = "ntencoder"
version = "0.1.0"
authors = ["brurucy <brurucy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lasso = "0.5.1"
clap = "3.0.0-beta.2"
linecount = "0.1.0"
